### ISSUE TITLE
App not recognize any keys except first "enter" and "ctrl + q"

### ISSUE THREAD

**Issue by qarmin** [bloznelis/kbt#4]
```
System:
  Host: rafal-H87M-D3H Kernel: 6.2.0-25-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 44.2 Distro: Ubuntu 23.04 (Lunar Lobster)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 bus-ID: 01:00.0
    temp: 45.0 C
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.8 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.4 (git-896db04e02) renderer: AMD Radeon RX
    570 Series (polaris10 LLVM 15.0.7 DRM 3.49 6.2.0-25-generic)
    direct-render: Yes

```
app installed via `cargo install`

When clicking first time enter, screen freeze until I change size of terminal

Later no clicks are recognized except ctrl + q

https://github.com/bloznelis/kbt/assets/41945903/550ec060-df50-4d22-b87f-fad16d78bf2a
